name: "contentmaster_warehouse"
version: "1.0.0"
config-version: 2

profile: "contentmaster_warehouse"

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]

models:
  contentmaster_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
